language: java

sudo: false

after success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - dzenziur@gmail.com
    on_success: never
    on_failure: always